// utils/shuffle.js
export function numberStyle() {
    // Make numbers speech funny like lucky seven, two little ducks, etc.
    const englishList = {
        1: 'a lonely one',
        2: 'two little ducks',
        3: 'a crooked tree',
        4: 'knock at the door',
        5: 'man on the dive',
        6: 'half a dozen',
        7: 'lucky seven',
        8: 'garden gate',
        9: 'a big fat nine',
        10: 'a big fat ten',
        11: 'legs eleven',
        12: 'one dozen',
        13: 'unlucky thirteen',
        14: 'valentine’s day',
        15: 'young and keen',
        16: 'sweet sixteen',
        17: 'dancing queen',
        18: 'coming of age',
        19: 'goodbye teens',
        20: 'one score',
        21: 'key of the door',
        22: 'two little ducks',
        23: 'thee and me',
        24: 'two dozen',
        25: 'duck and dive',
        26: 'half a century',
        27: 'gateway to heaven',
        28: 'over weight',
        29: 'rise and shine',
        30: 'dirty Gertie',
        31: 'get up and run',
        32: 'buckle my shoe',
        33: 'all the threes',
        34: 'ask for more',
        35: 'jump and jive',
        36: 'three dozen',
        37: 'more than eleven',
        38: 'three dozen and two',
        39: 'steps',
        40: 'naughty forty',
        41: 'time for fun',
        42: 'all the fours',
        43: 'down on your knees',
        44: 'droopy drawers',
        45: 'halfway there',
        46: 'up to tricks',
        47: 'four and seven',
        48: 'four dozen',
        49: 'pc 49',
        50: 'half a century',
        51: 'speed limit',
        52: 'deck of cards',
        53: 'here comes Herbie',
        54: 'clean the floor',
        55: 'all the fives',
        56: 'was she worth it?',
        57: 'heinz varieties',
        58: 'make them wait',
        59: 'brighton line',
        60: 'five dozen',
        61: 'baker’s bun',
        62: 'turn on the screw',
        63: 'tickle me 63',
        64: 'almost there',
        65: 'old age pension',
        66: 'clickety click',
        67: 'made in heaven',
        68: 'saving grace',
        69: 'nice and easy',
        70: 'three score and ten',
        71: 'bang on the drum',
        72: 'six dozen',
        73: 'queen bee',
        74: 'seven dozen and two',
        75: 'strive and strive',
        76: 'trombones',
        77: 'lucky 77',
        78: 'heaven’s gate',
        79: 'one more time',
        80: 'eight and blank',
        81: 'stop and run',
        82: 'straight on through',
        83: 'time for tea',
        84: 'seven dozen',
        85: 'stay alive',
        86: 'between the sticks',
        87: 'seven and eight',
        88: 'two fat ladies',
        89: 'nearly there',
        90: 'top of the shop'
    };
    // number style for Hindi speech like ek akela, do batakh, etc.
    const hindiList = {
        1: 'ek akela',
        2: 'do batakh',
        3: 'tedha pedha',
        4: 'darwaza khatkhataye',
        5: 'koodta hua aadmi',
        6: 'aadha dus',
        7: 'satrah shubh',
        8: 'bagicha ka gate',
        9: 'motaa nau',
        10: 'motaa das',
        11: 'gyarah ke taang',
        12: 'ek darjan',
        13: 'badkismat terah',
        14: 'valentine ka din',
        15: 'jawaan aur utsaahi',  
        16: 'meethi solah',
        17: 'naachti rani',
        18: 'vayaskta ka pravesh',
        19: 'achchha bees',
        20: 'ek score',
        21: 'darwaze ki chaabi',
        22: 'do batakh',
        23: 'tum aur main',
        24: 'do darjan',
        25: 'batakh aur kood',
        26: 'pachaas ka aadha hissa',
        27: 'swarg ka dwar',
        28: 'vajan se adhik',
        29: 'utho aur chamko',
        30: 'gandi Gertie',
        31: 'utho aur daudo',
        32: 'mere jute bandh lo',
        33: 'sab tees',
        34: 'aur maango',
        35: 'koodo aur jhumo',
        36: 'teen darjan',
        37: 'gyarah se adhik',
        38: 'teen darjan aur do',
        39: 'seedhiyaan',
        40: 'shaitaan chalis',
        41: 'mazaa karne ka samay',
        42: 'sab chaalis',
        43: 'ghutno ke bal',
        44: 'latakte underwaer',
        45: 'aadha raasta',
        46: 'chalakiyan karna',
        47: 'chaar aur saat',
        48: 'chaar darjan',
        49: 'pc 49',
        50: 'pachaas ka aadha hissa',
        51: 'gati seema',
        52: 'taash ka patta',
        53: 'yahaan aata hai Herbie',
        54: 'farsh saaf karo',
        55: 'sab pachas',
        56: 'kya vah iske layak thi?',
        57: 'heinz vibhinnataayein',
        58: 'unka intezaar karvao',
        59: 'brighton line',
        60: 'chhe darjan',
        61: 'baker ka bun',
        62: 'pech lagaao',
        63: 'mujhe gudgudao 63',
        64: 'lagbhag vahaan',
        65: 'vriddhavastha pension',
        66: 'clickety click',
        67: 'swarg mein bana',
        68: 'bachaa hua anugrah',
        69: 'aaraam se',
        70: 'teen score aur das',
        71: 'drum par dhamaka',
        72: 'chhe darjan',
        73: 'rani bee',
        74: 'saat darjan aur do',
        75: 'koshish karte raho',
        76: 'trombones',
        77: 'shubh 77',
        78: 'swarg ka gate',
        79: 'ek baar aur',
        80: 'aath aur khaali',
        81: 'ruk jao aur daudo',
        82: 'seedha aage badho',
        83: 'chai ka samay',
        84: 'saat darjan',
        85: 'zinda raho',
        86: 'sticks ke beech',
        87: 'saat aur aath',
        88: 'do mote auratein',
        89: 'lagbhag vahaan',
        90: 'dokan ka shikhar'
    };

    const numberList = [englishList, hindiList];

    return numberList;
}
